service: kairos

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    BUCKET_NAME: ${self:custom.buckets.${self:provider.stage}}
    STAGE: ${opt:stage, 'dev'}

functions:
  app:
    handler: src.Function.main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

custom:
  wsgi:
    app: src.Function.main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  buckets:
    dev: ${env:BUCKET_NAME_NONPROD}
    feature: ${env:BUCKET_NAME_NONPROD}
    main: ${env:BUCKET_NAME_MAIN}