service: kairos

org: null
app: null

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_APP_CLIENT_ID: ${env:COGNITO_APP_CLIENT_ID}
    COGNITO_REGION: ${env:COGNITO_REGION}
    BUCKET_NAME: ${self:custom.buckets.${self:provider.stage}}
    STAGE: ${opt:stage, 'dev'}

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

custom:
  wsgi:
    app: main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  buckets:
    dev: ${env:BUCKET_NAME_NONPROD}
    feature: ${env:BUCKET_NAME_NONPROD}
    main: ${env:BUCKET_NAME_MAIN}